/**
 * SUMO IS A BOXER — authored asset contract.
 *
 * Everything visible in this game is generated by code, so the asset library is
 * production code and gets tested like it. These assertions are the ones that
 * actually catch regressions: MeshIR validity, semantic naming, material
 * resolution, draw-call budget and determinism.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import {
  validateMesh, triangleCount, vertexCount, meshHash,
  PREVIEW_BUDGET_DEFAULTS
} from '@sumosizedginger/my-game-engine-1.0/full';

import { buildArenaAssets } from '../src/game/assets/arena.js';
import { buildWarehouseAssets } from '../src/game/assets/warehouse.js';
import { buildDressingAssets } from '../src/game/assets/dressing.js';
import { buildHeroKitAssets } from '../src/game/assets/hero-kit.js';
import { MATERIAL_DEFINITIONS, MATERIAL_FAMILIES, mat } from '../src/game/assets/materials.js';

/**
 * @returns {Map<string, object>}
 */
function buildAll() {
  const assets = new Map();
  for (const source of [buildArenaAssets(), buildWarehouseAssets(), buildDressingAssets(), buildHeroKitAssets()]) {
    for (const [key, mesh] of source) assets.set(key, mesh);
  }
  return assets;
}

const assets = buildAll();
const materialIds = new Set(MATERIAL_DEFINITIONS.map((definition) => definition.id));

test('the venue is authored from more than a handful of assets', () => {
  assert.ok(assets.size >= 20, `expected a dense venue, got ${assets.size} assets`);
});

test('every asset is a structurally valid MeshIR', () => {
  for (const [key, mesh] of assets) {
    const { valid, diagnostics } = validateMesh(mesh);
    assert.ok(valid, `${key}: ${diagnostics.map((d) => `${d.code} ${d.message}`).join('; ')}`);
  }
});

test('no anonymous parts: every part carries a meaningful semantic name', () => {
  for (const [key, mesh] of assets) {
    for (const part of mesh.parts) {
      assert.ok(part.semanticName && part.semanticName.trim().length > 2, `${key} has a part with no usable semanticName`);
      assert.ok(
        /^[a-z0-9]+(-[a-z0-9.]+)+$/i.test(part.semanticName),
        `${key}: part "${part.semanticName}" is not a readable kebab-case identity`
      );
    }
  }
});

test('every part material resolves to a MaterialDefinition this game authored', () => {
  for (const [key, mesh] of assets) {
    for (const part of mesh.parts) {
      assert.ok(part.materialId, `${key}: part "${part.semanticName}" has no material`);
      assert.ok(materialIds.has(part.materialId), `${key}: part "${part.semanticName}" references unknown material ${part.materialId}`);
    }
  }
});

test('the material language has distinct families, not one material tinted', () => {
  const families = Object.keys(MATERIAL_FAMILIES);
  assert.ok(families.length >= 25, `expected a real material language, got ${families.length} families`);

  // Roughness and metalness must genuinely differ between families; if every
  // family is the same surface with a different colour, this fails.
  const surfaces = new Set();
  for (const family of families) {
    const definition = MATERIAL_DEFINITIONS.find((d) => d.id === mat(family, 0));
    const { roughness, metalness } = definition.data.parameters;
    surfaces.add(`${roughness.toFixed(2)}:${metalness.toFixed(2)}`);
  }
  assert.ok(surfaces.size >= 15, `only ${surfaces.size} distinct surface responses across ${families.length} families`);
});

test('every asset stays inside the engine preview budget', () => {
  for (const [key, mesh] of assets) {
    assert.ok(mesh.parts.length <= PREVIEW_BUDGET_DEFAULTS.maxParts, `${key} has ${mesh.parts.length} parts`);
    assert.ok(triangleCount(mesh) <= PREVIEW_BUDGET_DEFAULTS.maxTriangles, `${key} has ${triangleCount(mesh)} triangles`);
    assert.ok(vertexCount(mesh) <= PREVIEW_BUDGET_DEFAULTS.maxVertices, `${key} has ${vertexCount(mesh)} vertices`);
  }
});

test('aggregate authored geometry stays inside the character ceiling regression limit', () => {
  let triangles = 0;
  let parts = 0;
  for (const mesh of assets.values()) {
    triangles += triangleCount(mesh);
    parts += mesh.parts.length;
  }
  assert.ok(triangles < 180000, `authored triangles ${triangles} is above the character-ceiling regression limit (not a GPU performance claim)`);
  assert.ok(parts < 200, `authored parts ${parts} implies too many draw calls`);
});

test('asset generation is deterministic: same code, same bytes', () => {
  const second = buildAll();
  for (const [key, mesh] of assets) {
    assert.equal(meshHash(mesh), meshHash(second.get(key)), `${key} is not reproducible`);
  }
});

test('the semantic vocabulary the brief asks for is actually present', () => {
  const names = new Set();
  for (const mesh of assets.values()) for (const part of mesh.parts) names.add(part.semanticName);
  const required = [
    'arena-deck-slab', 'arena-edge-curb', 'arena-support-legs',
    'warehouse-floor-slab', 'warehouse-wall-concrete', 'warehouse-column-concrete',
    'warehouse-truss-chords', 'lighting-gantry-frame', 'warehouse-pipe-runs',
    'heavy-bag-leather', 'crowd-silhouettes', 'ringside-barrier-bars', 'bleacher-planks'
  ];
  for (const name of required) {
    assert.ok(names.has(name), `semantic part "${name}" is missing from the authored assets`);
  }
});

test('first-person limbs are voxel-authored fists, not boxing gloves', () => {
  assert.equal(assets.has('asset.boxer.glove.right'), false);
  assert.equal(assets.has('asset.boxer.trunks'), false);
  const arm = assets.get('asset.fp.arm.left');
  const armNames = arm.parts.map((p) => p.semanticName);
  assert.ok(armNames.some((n) => n.includes('forearm')), 'the first-person arm has no forearm');
  assert.ok(armNames.some((n) => n.includes('fist')), 'the first-person arm has no fist');
  assert.ok(arm.anchors.some((a) => a.name === 'fist.contact'), 'the arm has no contact anchor');
});
