/**
 * SUMO IS A BOXER — HUD.
 *
 * DOM UI over the WebGL stage. Built once, then only mutated: no innerHTML in
 * the per-frame path, no element churn, no layout thrash. Bars are driven by
 * `transform: scaleX`, which is a compositor property, so the fight HUD costs
 * nothing while the fight is happening.
 */

const CONTROLS = [
  ['Move', 'WASD'],
  ['Look', 'Mouse'],
  ['Jab', 'LMB'],
  ['Heavy cross', 'RMB'],
  ['Block', 'MMB / hold RMB'],
  ['Dodge', 'Space'],
  ['Guard high', 'E / Wheel up'],
  ['Guard low', 'Q / Wheel down'],
  ['Sprint', 'Shift'],
  ['Pause', 'Esc'],
  ['Rematch', 'R'],
  ['Gamepad', 'Fully supported']
];

/**
 * @param {HTMLElement} host
 * @returns {object} HUD handle.
 */
export function createHud(host) {
  const hud = el('div', 'hud menu');

  // --- opponent ------------------------------------------------------------
  const opponentPanel = el('div', 'opponent-panel');
  const opponentName = el('div', 'name');
  opponentName.append(text('span', '', 'THE RED CORNER'), text('span', 'corner', 'CHALLENGER'));
  const opponentHealth = bar('health enemy-health');
  const opponentGuard = bar('guard enemy-guard slim');
  opponentPanel.append(opponentName, opponentHealth.root, opponentGuard.root);

  // --- round strip ---------------------------------------------------------
  const roundStrip = el('div', 'round-strip');
  const knocksOpponent = el('div', 'knocks');
  const knocksPlayer = el('div', 'knocks');
  const knockCellsOpponent = [];
  const knockCellsPlayer = [];
  for (let i = 0; i < 3; i += 1) {
    const a = el('b'); knocksOpponent.append(a); knockCellsOpponent.push(a);
    const b = el('b'); knocksPlayer.append(b); knockCellsPlayer.push(b);
  }
  const clock = text('div', 'clock', '2:30');
  roundStrip.append(knocksOpponent, clock, knocksPlayer);

  // --- player --------------------------------------------------------------
  const playerPanel = el('div', 'player-panel');
  const healthRow = el('div', 'row');
  healthRow.append(text('div', 'label', 'Condition'), text('span', '', 'BLUE CORNER'));
  const playerHealth = bar('health');
  const playerStamina = bar('stamina');
  const playerGuard = bar('guard slim');
  playerPanel.append(
    healthRow, playerHealth.root,
    text('div', 'label', 'Wind'), playerStamina.root,
    text('div', 'label', 'Guard'), playerGuard.root
  );

  const guardIndicator = el('div', 'guard-indicator');
  const guardState = text('div', 'state', 'GUARD ▲ HIGH');
  const guardHint = text('div', 'hint', 'Q low · E high · wheel');
  guardIndicator.append(guardState, guardHint);

  // --- centre --------------------------------------------------------------
  const reticle = el('div', 'reticle');
  reticle.append(el('i'), el('i'));
  const message = text('div', 'combat-message', '');
  const vignette = el('div', 'vignette');
  const damageFlash = el('div', 'damage-flash');

  // --- overlays ------------------------------------------------------------
  const startOverlay = el('div', 'overlay title show');
  const startTitle = el('h1');
  startTitle.append(document.createTextNode('SUMO IS A BOXER'), text('em', '', 'Midnight Bout'));
  const startSub = text('div', 'sub',
    'An illegal bout in a dead warehouse. One opponent. Three knockdowns ends it. '
    + 'Everything you can see was generated by code.');
  const controlGrid = el('div', 'controls');
  for (const [action, key] of CONTROLS) {
    const row = el('div');
    row.append(text('span', '', action), text('kbd', '', key));
    controlGrid.append(row);
  }
  const startButton = text('button', 'prompt', 'CLICK TO FIGHT');
  startOverlay.append(startTitle, startSub, controlGrid, startButton);

  const pauseOverlay = el('div', 'overlay');
  const pauseTitle = text('h2', '', 'PAUSED');
  const pauseButton = text('button', 'prompt', 'RESUME');
  pauseOverlay.append(pauseTitle, text('div', 'sub', 'Esc to resume · R to restart the bout'), pauseButton);

  const resultOverlay = el('div', 'overlay');
  const resultTitle = text('h1', '', 'VICTORY');
  const resultLine = el('div', 'result-line');
  const statTime = stat('Time');
  const statHealth = stat('Your condition');
  const statKnocks = stat('Knockdowns');
  // VICTORY alone does not say how it was won, and the difference between being
  // counted out and being stopped on the three-knockdown rule is the whole point
  // of the finish.
  const statVerdict = stat('Verdict');
  resultLine.append(statTime.root, statHealth.root, statKnocks.root, statVerdict.root);
  const rematchButton = text('button', 'prompt', 'REMATCH');
  resultOverlay.append(resultTitle, resultLine, rematchButton);

  const diagnostics = el('pre', 'diagnostics');
  const cornerTag = text('div', 'corner-tag', 'MY GAME ENGINE 1.0 · PROCEDURAL BENCHMARK');

  hud.append(
    opponentPanel, roundStrip, playerPanel, guardIndicator,
    reticle, message, vignette, damageFlash,
    startOverlay, pauseOverlay, resultOverlay, diagnostics, cornerTag
  );
  host.append(hud);

  let messageShown = '';
  let lastDamage = -1;
  let showingReticle = true;

  return {
    root: hud,
    startButton,
    pauseButton,
    rematchButton,

    /**
     * @param {object} snapshot - Match snapshot.
     * @param {number} damage - Damage vignette strength, 0..1.
     */
    update(snapshot, damage) {
      playerHealth.set(snapshot.player.health / 100);
      playerStamina.set(snapshot.player.stamina / 100);
      playerGuard.set(snapshot.player.guardMeter / 100);
      opponentHealth.set(snapshot.opponent.health / 100);
      opponentGuard.set(snapshot.opponent.guardMeter / 100);

      playerHealth.low(snapshot.player.health < 26);
      playerStamina.low(snapshot.player.stamina < 20);
      opponentGuard.low(snapshot.opponent.guardMeter < 22);

      const seconds = Math.max(0, Math.ceil(snapshot.roundTime));
      const next = `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
      if (clock.textContent !== next) clock.textContent = next;
      clock.classList.toggle('urgent', seconds <= 15);

      for (let i = 0; i < 3; i += 1) {
        knockCellsOpponent[i].classList.toggle('on', snapshot.opponent.knockdowns > i);
        knockCellsPlayer[i].classList.toggle('on', snapshot.player.knockdowns > i);
      }

      const blocking = snapshot.player.blocking;
      const label = blocking
        ? (snapshot.player.guard === 'low' ? 'BLOCK ▼ LOW' : 'BLOCK ▲ HIGH')
        : (snapshot.player.guard === 'low' ? 'GUARD ▼ LOW' : 'GUARD ▲ HIGH');
      if (guardState.textContent !== label) guardState.textContent = label;
      guardState.classList.toggle('blocking', blocking);

      const wantsMessage = snapshot.messageT > 0 ? snapshot.message : '';
      if (wantsMessage !== messageShown) {
        messageShown = wantsMessage;
        message.textContent = wantsMessage;
        message.classList.toggle('show', Boolean(wantsMessage));
      }

      const rounded = Math.round(damage * 100) / 100;
      if (rounded !== lastDamage) {
        lastDamage = rounded;
        damageFlash.style.opacity = String(rounded * 0.85);
      }

      const wantsReticle = snapshot.state === 'FIGHTING';
      if (wantsReticle !== showingReticle) {
        showingReticle = wantsReticle;
        reticle.style.display = wantsReticle ? '' : 'none';
      }
    },

    /**
     * @param {'start'|'pause'|'result'|null} which
     */
    showOverlay(which) {
      startOverlay.classList.toggle('show', which === 'start');
      pauseOverlay.classList.toggle('show', which === 'pause');
      resultOverlay.classList.toggle('show', which === 'result');
      // The title and result screens are not the fight: the fight HUD stands
      // down so the arena behind them is the picture.
      hud.classList.toggle('menu', which === 'start' || which === 'result');
      // Any overlay silences the combat banner: a "GUARD BREAK!" ghosting
      // behind a PAUSED title is the kind of small wrongness that reads as
      // unfinished.
      hud.classList.toggle('overlaid', Boolean(which));
    },

    /**
     * @param {object} snapshot
     */
    showResult(snapshot) {
      const result = snapshot.result ?? { result: 'DRAW', label: 'DRAW' };
      resultTitle.textContent = result.result === 'WIN' ? 'VICTORY' : result.result === 'LOSE' ? 'DEFEAT' : 'DRAW';
      const seconds = Math.max(0, Math.round(snapshot.roundTime));
      statTime.set(`${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')} LEFT`);
      statHealth.set(`${Math.round(snapshot.player.health)}%`);
      statKnocks.set(`${snapshot.opponent.knockdowns} – ${snapshot.player.knockdowns}`);
      statVerdict.set(result.label);
      rematchButton.textContent = 'REMATCH';
    },

    /**
     * @param {string|null} content - null hides the overlay.
     */
    setDiagnostics(content) {
      diagnostics.classList.toggle('show', Boolean(content));
      if (content) diagnostics.textContent = content;
    },

    dispose() {
      hud.remove();
    }
  };
}

/**
 * @param {string} tag
 * @param {string} [className]
 * @returns {HTMLElement}
 */
function el(tag, className = '') {
  const node = document.createElement(tag);
  if (className) node.className = className;
  return node;
}

/**
 * @param {string} tag
 * @param {string} className
 * @param {string} content
 * @returns {HTMLElement}
 */
function text(tag, className, content) {
  const node = el(tag, className);
  node.textContent = content;
  if (tag === 'button') node.type = 'button';
  return node;
}

/**
 * @param {string} className
 * @returns {object}
 */
function bar(className) {
  const root = el('div', `bar ${className}`);
  const fill = el('i');
  fill.style.transform = 'scaleX(1)';
  root.append(fill);
  let last = 1;
  return {
    root,
    /** @param {number} value 0..1 */
    set(value) {
      const clamped = Math.max(0, Math.min(1, value));
      if (Math.abs(clamped - last) < 0.004) return;
      last = clamped;
      fill.style.transform = `scaleX(${clamped})`;
    },
    /** @param {boolean} on */
    low(on) {
      root.classList.toggle('low', on);
    }
  };
}

/**
 * @param {string} label
 * @returns {object}
 */
function stat(label) {
  const root = el('div');
  const value = el('b');
  root.append(document.createTextNode(label), value);
  return {
    root,
    /** @param {string} content */
    set(content) { value.textContent = content; }
  };
}
